name: assume
description: Assume App Plan & Do

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  custom_timer: ^0.2.3
  encrypt: ^5.0.1
  firebase_auth: ^4.2.10
  firebase_core: ^2.7.0
  fl_chart: ^0.61.0
  flavor: ^2.0.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_datetime_picker: ^1.5.1
  flutter_dotenv: ^5.0.2
  flutter_gen_runner: ^5.1.0+1
  flutter_local_notifications: ^13.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  logger: ^1.3.0
  mailer: ^6.0.0
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  provider: ^6.0.5
  share_plus: ^6.3.1
  showcaseview: ^2.0.3
  table_calendar: ^3.0.8
  timezone: ^0.9.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/images/
    - assets/env/
